// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtYP0K40Jv1Dr60Asp1g7dt6g-nGU_M7E',
    appId: '1:187831544308:web:7ae830293284231e8531a1',
    messagingSenderId: '187831544308',
    projectId: 'fir-pushnotification-edebd',
    authDomain: 'fir-pushnotification-edebd.firebaseapp.com',
    storageBucket: 'fir-pushnotification-edebd.appspot.com',
    measurementId: 'G-NR14QGELKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjX5HN4O67si9djSTqWt0mZoamiTR5vw4',
    appId: '1:187831544308:android:6fa24d8ec32267138531a1',
    messagingSenderId: '187831544308',
    projectId: 'fir-pushnotification-edebd',
    storageBucket: 'fir-pushnotification-edebd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASVFT1nBVwmWksgCoIazKRwDsEYsx3d1c',
    appId: '1:187831544308:ios:d16c9c8c3edf000a8531a1',
    messagingSenderId: '187831544308',
    projectId: 'fir-pushnotification-edebd',
    storageBucket: 'fir-pushnotification-edebd.appspot.com',
    iosBundleId: 'com.example.firebasePushNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASVFT1nBVwmWksgCoIazKRwDsEYsx3d1c',
    appId: '1:187831544308:ios:d16c9c8c3edf000a8531a1',
    messagingSenderId: '187831544308',
    projectId: 'fir-pushnotification-edebd',
    storageBucket: 'fir-pushnotification-edebd.appspot.com',
    iosBundleId: 'com.example.firebasePushNotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtYP0K40Jv1Dr60Asp1g7dt6g-nGU_M7E',
    appId: '1:187831544308:web:cff3a3737b91e6da8531a1',
    messagingSenderId: '187831544308',
    projectId: 'fir-pushnotification-edebd',
    authDomain: 'fir-pushnotification-edebd.firebaseapp.com',
    storageBucket: 'fir-pushnotification-edebd.appspot.com',
    measurementId: 'G-M18484K8BG',
  );
}
